import {
  ArrowRight,
  BookOpen,
  CheckCircle,
  EllipsisVertical,
  Fingerprint,
  Laptop,
  LayoutDashboard,
  LogOut,
  Menu,
  Moon,
  Settings,
  Sun,
  UserCircle,
  Users,
  Wallet,
  X,
  Zap,
} from "lucide-react";

export const Icons = {
  arrowRight: ArrowRight,
  checkCircle: CheckCircle,
  close: X,
  dashboard: LayoutDashboard,
  home: BookOpen,
  dotsVertical: EllipsisVertical,
  laptop: Laptop,
  logo: Fingerprint,
  logout: LogOut,
  menu: Menu,
  moon: Moon,
  payments: Wallet,
  settings: Settings,
  sun: Sun,
  user: UserCircle,
  users: Users,
  zap: Zap,
};
