import {
  ArrowRight,
  CheckCircle,
  EllipsisVertical,
  House,
  Laptop,
  LayoutDashboard,
  Library,
  LogOut,
  Menu,
  MoonStar,
  Settings,
  Sparkles,
  Sun,
  UserCircle,
  Users,
  Wallet,
  X,
  Zap,
} from "lucide-react";

export const Icons = {
  arrowRight: ArrowRight,
  checkCircle: CheckCircle,
  close: X,
  dashboard: LayoutDashboard,
  dotsVertical: EllipsisVertical,
  home: House,
  laptop: Laptop,
  library: Library,
  logo: Sparkles,
  logout: LogOut,
  menu: Menu,
  moon: MoonStar,
  payments: Wallet,
  settings: Settings,
  sun: Sun,
  user: UserCircle,
  users: Users,
  zap: Zap,
};
